/**
 * Keyword / phrase → emoji for goal titles. Order matters: longer / more specific patterns first.
 * Matching logic lives in `goalEmojiSuggest.ts`.
 */

export type EmojiRule = { patterns: string[]; emoji: string };

export const RULES: EmojiRule[] = [
  {
    patterns: [
      'half marathon',
      'triathlon',
      'duathlon',
      'aquathlon',
      'triathlete',
      'ironman',
      'open water swim',
    ],
    emoji: '🏊',
  },
  {
    patterns: [
      'full marathon',
      'marathon',
      'running race',
      'race day',
      '5 km',
      '10 km',
      'parkrun',
      'race pace',
      'tempo run',
      'interval training',
    ],
    emoji: '🏃',
  },
  {
    patterns: [
      'electric guitar',
      'learn guitar',
      'play guitar',
      'guitar lesson',
      'guitar',
      'bass guitar',
      'bass line',
      'bass',
      'ukulele',
      'banjo',
      'mandolin',
      'strum',
      'guitar amp',
      'acoustic',
      'fretboard',
      'tablature',
      'fingerpicking',
    ],
    emoji: '🎸',
  },
  {
    patterns: [
      'grand piano',
      'piano',
      'keyboard',
      'midi keyboard',
      'synth',
      'synthesizer',
      'keyboardist',
      'organ',
    ],
    emoji: '🎹',
  },
  {
    patterns: ['violin', 'viola', 'cello', 'double bass', 'orchestra', 'symphony', 'conductor', 'string quartet'],
    emoji: '🎻',
  },
  {
    patterns: [
      'drum kit',
      'drum set',
      'drum',
      'drummer',
      'percussion',
      'beatmaking',
      'cymbal',
    ],
    emoji: '🥁',
  },
  {
    patterns: [
      'songwriting',
      'songwriter',
      'song',
      'music theory',
      'music',
      'album',
      'playlist',
      'band',
      'sing',
      'singer',
      'singing',
      'vocal',
      'karaoke',
      'choir',
      'melody',
      'lyrics',
    ],
    emoji: '🎵',
  },
  { patterns: ['concert hall', 'concert', 'festival', 'live show', 'dj ', 'disc jockey', 'headliner', 'backstage'], emoji: '🎤' },
  {
    patterns: [
      'saxophone',
      'sax',
      'trumpet',
      'trombone',
      'flute',
      'clarinet',
      'oboe',
      'harmonica',
      'accordion',
    ],
    emoji: '🎷',
  },

  {
    patterns: [
      'book club',
      'read more',
      'speed reading',
      'reading',
      'read',
      'book',
      'novel',
      'paperback',
      'ebook',
      'kindle',
      'audiobook',
      'literature',
      'fiction',
      'nonfiction',
      'goodreads',
    ],
    emoji: '📚',
  },
  {
    patterns: [
      'novel draft',
      'writing',
      'writer',
      'blog',
      'substack',
      'journal',
      'ghostwrite',
      'screenplay',
      'copywriting',
      'essay',
    ],
    emoji: '✍️',
  },
  {
    patterns: [
      'final exam',
      'study abroad',
      'study',
      'midterm',
      'exam',
      'homework',
      'course',
      'degree',
      'thesis',
      'dissertation',
      'school',
      'university',
      'college',
      'lecture',
      'class',
      'semester',
      'tuition',
      'scholarship',
    ],
    emoji: '🎓',
  },
  {
    patterns: [
      'learn language',
      'language',
      'bilingual',
      'spanish',
      'french',
      'german',
      'japanese',
      'mandarin',
      'cantonese',
      'italian',
      'korean',
      'portuguese',
      'russian',
      'arabic',
      'hindi',
      'duolingo',
    ],
    emoji: '🌍',
  },
  {
    patterns: [
      'photograph',
      'photography',
      'photoshoot',
      'photo',
      'dslr',
      'mirrorless',
      'camera',
      'portrait',
      'lens',
      'lightroom',
    ],
    emoji: '📷',
  },
  {
    patterns: ['oil paint', 'paint ', 'painting', 'canvas', 'watercolor', 'acrylic', 'easel', 'brushwork', 'palette'],
    emoji: '🖌️',
  },
  {
    patterns: ['draw ', 'drawing', 'sketch', 'illustrator', 'illustrat', 'doodle', 'storyboard', 'figure drawing'],
    emoji: '✏️',
  },
  { patterns: ['pottery wheel', 'pottery', 'ceramic', 'kiln', 'clay', 'glaze'], emoji: '🏺' },
  {
    patterns: ['knit', 'knitting', 'crochet', 'yarn', 'sew ', 'sewing', 'needlework', 'embroidery', 'cross stitch'],
    emoji: '🧶',
  },

  {
    patterns: [
      'lap swim',
      'swim lesson',
      'swim',
      'swimming',
      'freestyle',
      'backstroke',
      'pool lane',
      'swim meet',
    ],
    emoji: '🏊',
  },
  {
    patterns: [
      'trail run',
      'long run',
      'easy run',
      'run ',
      'running',
      'jog',
      '5k',
      '10k',
      'halfmarathon',
      'sprint',
      'ultra',
      'ultra marathon',
    ],
    emoji: '🏃',
  },
  {
    patterns: [
      'nature walk',
      'walk ',
      'walking',
      'hike ',
      'hiking',
      'trail',
      'trek',
      'backpack',
      'canyon',
    ],
    emoji: '🥾',
  },
  {
    patterns: [
      'mountain bike',
      'road bike',
      'bike ',
      'biking',
      'cycling',
      'bicycle',
      'spin class',
      'peloton',
    ],
    emoji: '🚴',
  },
  {
    patterns: [
      'yoga',
      'pilates',
      'stretch',
      'meditat',
      'mindful',
      'breathwork',
      'breathing exercise',
    ],
    emoji: '🧘',
  },
  {
    patterns: [
      'personal trainer',
      'strength training',
      'gym',
      'workout',
      'lift ',
      'lifting',
      'muscle',
      'fitness',
      'crossfit',
      'hiit',
      'calisthenics',
    ],
    emoji: '💪',
  },
  {
    patterns: ['soccer', 'fifa', 'football match', 'football', 'futbol', 'premier league', 'world cup'],
    emoji: '⚽',
  },
  { patterns: ['basketball', 'nba', 'ncaa basketball', 'hoops'], emoji: '🏀' },
  { patterns: ['tennis', 'wimbledon', 'us open tennis', 'grand slam tennis', 'pickleball'], emoji: '🎾' },
  { patterns: ['volleyball', 'beach volleyball', 'spike'], emoji: '🏐' },
  { patterns: ['field hockey', 'hockey stick', 'ice hockey', 'hockey', 'rink', 'nhl'], emoji: '🏒' },
  { patterns: ['mini golf', 'disc golf', 'golf swing', 'golf', 'putting', 'golf course'], emoji: '⛳' },
  { patterns: ['kickboxing', 'boxing', 'mma', 'martial art', 'bjj', 'judo', 'karate', 'wrestling'], emoji: '🥊' },
  {
    patterns: ['kite surf', 'wind surf', 'surf trip', 'surf ', 'surfing', 'waves', 'bodyboard'],
    emoji: '🏄',
  },
  {
    patterns: ['snow ski', 'ski trip', 'ski ', 'skiing', 'snowboard', 'slopes', 'powder day', 'apres ski'],
    emoji: '⛷️',
  },
  {
    patterns: ['hip hop dance', 'ballroom', 'dance ', 'dancing', 'choreograph', 'ballet', 'tango', 'salsa dancing'],
    emoji: '💃',
  },

  {
    patterns: [
      'eat more greens',
      'salad',
      'vegan',
      'vegetarian',
      'plant based',
      'eat healthy',
      'whole food',
      'nutrition',
      'macro',
      'diet',
      'meal prep',
      'meal plan',
    ],
    emoji: '🥗',
  },
  {
    patterns: [
      'meal prep sunday',
      'meal kit',
      'prep cooking',
      'cook ',
      'cooking',
      'recipe',
      'bake ',
      'baking',
      'chef',
      'sous vide',
      'air fry',
    ],
    emoji: '🍳',
  },
  {
    patterns: ['coffee', 'cold brew', 'latte', 'cappuccino', 'espresso', 'cafe', 'barista', 'pour over'],
    emoji: '☕',
  },
  {
    patterns: ['wine tasting', 'wine', 'beer', 'craft beer', 'brew ', 'brewery', 'ipa', 'cocktail', 'mixology'],
    emoji: '🍷',
  },
  { patterns: ['sushi', 'sashimi', 'bento', 'ramen', 'poke bowl', 'japanese food', 'udon', 'tempura'], emoji: '🍱' },
  { patterns: ['bbq', 'barbecue', 'smoker', 'ribs', 'grill '], emoji: '🍖' },

  {
    patterns: [
      'travel hack',
      'digital nomad',
      'travel',
      'trip ',
      'vacation',
      'holiday',
      'flight',
      'airport',
      'boarding pass',
      'luggage',
      'hotel',
      'airbnb',
      'passport',
      'visa',
      'layover',
    ],
    emoji: '✈️',
  },
  { patterns: ['road trip', 'roadtrip', 'drive cross', 'cross country drive', 'car trip', 'van life'], emoji: '🚗' },
  { patterns: ['metro ', 'subway', 'train ', 'rail', 'commute', 'eurostar'], emoji: '🚆' },
  {
    patterns: ['snorkeling', 'scuba', 'beach vacation', 'beach ', 'ocean', 'island hop', 'island ', 'surf trip'],
    emoji: '🏝️',
  },
  { patterns: ['backcountry', 'wild camp', 'camp ', 'camping', 'campfire', 'rv trip'], emoji: '⛺' },
  {
    patterns: ['rock climb', 'mountaineer', 'mountain ', 'summit', 'alpine', 'climb ', 'climbing', 'boulder problem'],
    emoji: '🏔️',
  },
  { patterns: ['art museum', 'museum', 'gallery opening', 'gallery ', 'exhibit', 'curator'], emoji: '🖼️' },
  {
    patterns: ['sightseeing', 'city tour', 'walking tour', 'tour guide', 'tour ', 'itinerary', 'bucket list trip'],
    emoji: '🗺️',
  },

  {
    patterns: [
      'start up',
      'startup',
      'launch day',
      'launch',
      'mvp',
      'minimum viable',
      'go to market',
      'product market fit',
      'product vision',
      'ship it',
      'shipped',
      'side project',
      'hackathon',
      'sprint planning',
      'sprint',
    ],
    emoji: '🚀',
  },
  {
    patterns: [
      'pull request',
      'open source',
      'refactor',
      'code review',
      'code',
      'coding',
      'software engineer',
      'software',
      'developer',
      'programming',
      'webdev',
      'frontend',
      'backend',
      'fullstack',
      'app store',
      'app ',
      'website',
      'debug',
      'stack trace',
      'api',
      'graphql',
      'typescript',
      'javascript',
      'react',
      'node ',
      'python',
      'rust lang',
    ],
    emoji: '💻',
  },
  {
    patterns: [
      'design system',
      'wireframe',
      'high fidelity',
      'visual design',
      'design',
      'ux research',
      'ux ',
      'ui ',
      'figma',
      'prototype',
      'mockup',
    ],
    emoji: '🎨',
  },
  {
    patterns: [
      'all hands',
      'quarterly review',
      'standup meeting',
      'standup',
      'meeting',
      'all-hands',
      'presentation',
      'deck ',
      'pitch deck',
      'pitch ',
      'slide deck',
      'slide ',
      'stakeholder',
    ],
    emoji: '📊',
  },
  {
    patterns: [
      'save money',
      'emergency fund',
      'budget',
      'finance',
      'financial plan',
      'invest',
      'etf',
      'stock',
      'dividend',
      'portfolio',
      'retirement account',
      '401k',
    ],
    emoji: '💰',
  },
  {
    patterns: [
      'job search',
      'job offer',
      'job ',
      'interview prep',
      'interview',
      'resume',
      'cv ',
      'cover letter',
      'career change',
      'career',
      'promotion',
      'linkedin',
      'networking event',
    ],
    emoji: '💼',
  },
  { patterns: ['out of office', 'email', 'inbox zero', 'inbox', 'newsletter', 'mailing list'], emoji: '📧' },
  {
    patterns: [
      'production deploy',
      'deploy ',
      'deployment',
      'release notes',
      'release',
      'ci cd',
      'github actions',
      'pipeline',
      'rollback',
    ],
    emoji: '⚙️',
  },
  { patterns: ['regression', 'bug bash', 'bug ', 'fix bug', 'triage', 'heisenbug'], emoji: '🐛' },
  { patterns: ['indie game', 'game dev', 'unity', 'unreal engine', 'gaming', 'speedrun', 'esports'], emoji: '🎮' },
  { patterns: ['live stream', 'stream ', 'streaming', 'twitch', 'youtube channel', 'vlog'], emoji: '📹' },

  {
    patterns: [
      'family time',
      'family',
      'newborn',
      'baby',
      'toddler',
      'kid ',
      'kids',
      'parent',
      'parenthood',
      'homeschool',
    ],
    emoji: '👪',
  },
  {
    patterns: ['wedding venue', 'wedding plan', 'wedding', 'marriage', 'engaged', 'engagement', 'bride', 'groom', 'honeymoon'],
    emoji: '💒',
  },
  {
    patterns: [
      'fixer upper',
      'home improvement',
      'home ',
      'house ',
      'renovat',
      'remodel',
      'move in',
      'apartment hunt',
      'apartment',
      'condo',
      'mortgage',
      'refinance',
    ],
    emoji: '🏠',
  },
  {
    patterns: ['raised bed', 'vegetable garden', 'garden ', 'gardening', 'plants', 'plant ', 'compost', 'greenhouse'],
    emoji: '🌱',
  },
  {
    patterns: [
      'pet care',
      'dog walk',
      'dog ',
      'puppy',
      'cat ',
      'kitten',
      'reptile',
      'hamster',
      'vet visit',
      'vet ',
      'adopt a pet',
    ],
    emoji: '🐾',
  },
  { patterns: ['date night', 'valentine', 'partner', 'spouse', 'anniversary'], emoji: '💕' },
  { patterns: ['friend group', 'friend ', 'friends', 'hangout', 'house party', 'party ', 'birthday party'], emoji: '🎈' },

  {
    patterns: [
      'sleep schedule',
      'sleep hygiene',
      'sleep ',
      'insomnia',
      'circadian',
      'rest day',
      'rest ',
      'nap ',
      'power nap',
    ],
    emoji: '😴',
  },
  {
    patterns: [
      'therapy session',
      'therapy',
      'therapist',
      'psychologist',
      'psychiatry',
      'mental health',
      'counsel',
      'cognitive behavioral',
      'mindfulness',
    ],
    emoji: '🧠',
  },
  {
    patterns: [
      'annual physical',
      'doctor appointment',
      'doctor',
      'physician',
      'urgent care',
      'er visit',
      'health insurance',
      'health check',
      'dentist',
      'checkup',
      'pharmacy',
      'prescription',
    ],
    emoji: '🏥',
  },
  { patterns: ['vitamin', 'supplement', 'hydrat', 'electrolyte', 'immune'], emoji: '💊' },

  {
    patterns: [
      'lifelong learn',
      'learn something',
      'learn ',
      'self taught',
      'skill build',
      'skill ',
      'upskill',
      'master class',
      'master ',
      'practice ',
      'drill ',
    ],
    emoji: '📖',
  },
  {
    patterns: [
      'side project goal',
      'okr',
      'project plan',
      'project ',
      'initiative',
      'deliverable',
      'goal ',
      'objective',
      'milestone',
      'roadmap',
    ],
    emoji: '🎯',
  },
  {
    patterns: [
      'atomic habit',
      'habit track',
      'habit',
      'routine',
      'every morning',
      'daily streak',
      'daily',
      'streak',
      'calendar block',
      'calendar',
    ],
    emoji: '🔥',
  },
  {
    patterns: [
      'deep clean',
      'spring clean',
      'clean ',
      'cleaning',
      'declutter',
      'minimalist',
      'organize',
      'tidy',
      'marie kondo',
    ],
    emoji: '🧹',
  },
  {
    patterns: [
      'home repair',
      'handyman',
      'fix ',
      'fixing',
      'repair',
      'diy',
      'hardware store',
      'leak fix',
    ],
    emoji: '🔧',
  },
  {
    patterns: [
      'car repair',
      'car maintenance',
      'car ',
      'vehicle',
      'automotive',
      'oil change',
      'mechanic',
      'brake ',
      'tire ',
    ],
    emoji: '🚙',
  },
  { patterns: ['retail therapy', 'shop ', 'shopping', 'wardrobe', 'closet cleanout', 'closet'], emoji: '🛍️' },
  {
    patterns: [
      'save for',
      'money goal',
      'money ',
      'cash flow',
      'debt free',
      'debt',
      'bills',
      'subscription audit',
    ],
    emoji: '💳',
  },
  { patterns: ['tax season', 'tax return', 'tax ', 'accountant', 'cpa', 'irs', 'audit'], emoji: '📑' },
  {
    patterns: [
      'volunteer',
      'volunteering',
      'charity',
      'fundraiser',
      'nonprofit',
      'ngo',
      'community service',
      'give back',
    ],
    emoji: '🤝',
  },
];
